spring: 
  application:
    name: airagotes
  ai:
    model:
      chat: ollama
    ollama:

      init:
        pull-model-strategy: when_missing
        embedding:
          additional-models:
            - "nomic-embed-text:latest"
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:4b

    
