spring: 
  application:
    name: airagotes
  ai:
    vectorstore:
      qdrant:
        host: 127.0.0.1
        port: 6334
        collection-name: notes
        intialize-schema: true
    ollama:
      init:
        pull-model-strategy: when_missing
        embedding:
          additional-models:
            - "nomic-embed-text:latest"
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:4b
knowledgebase:
  init: true
  folder: "/home/tomasz/Documents/ObsidianNotes"
